name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    #container: mcr.microsoft.com/dotnet/aspnet:7.0
    #env:
    #  USERPROFILE: "./"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      # dotnet 7 has builtin docker target support using Microsoft.NET.Build.Containers package
      - name: Publish
        run: dotnet publish ./WebApi/WebApi.csproj --no-restore -c Release -o ./dist
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          if-no-files-found: error
          retention-days: 7
